version: '3.8'
name: tickets-backend
services:
  mongodb:
    container_name: tickets-backend-mongodb
    image: mongo:5.0.14
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=tickets
    volumes:
      - mongodb_data:/data/db
  mockoon:
    container_name: tickets-backend-mockoon
    image: mockoon/cli:4.1.0
    entrypoint: "mockoon-cli start -d /mock.json -l 0.0.0.0 --daemon-off"
    ports:
      - 8001:8001
    volumes:
      - './mock/mockoon.json:/mock.json'

volumes:
  mongodb_data:
